{% set version = "0.11.0" %}
{% set sha256 = "ae709b6f933694f1810eb3c8f517bdb76c13576d74a7a5a1704e05239df0a179" %}

package:
  name: pysurfer
  version: {{ version }}

source:
  fn: pysurfer-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pysurfer/pysurfer-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script:
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - imageio
    - matplotlib-base
    - mayavi
    - nibabel
    - numpy
    - scipy

test:
  commands:
#    - DISPLAY=localhost:1.0 xvfb-run -a python -c "import surfer"  # [linux]
    - python -c "import surfer"  # [not linux]

about:
  home: http://pysurfer.github.com
  license: BSD-3-clause
  license_file: LICENSE
  license_family: BSD
  summary: Cortical surface visualization using Python

  description: |
    PySurfer is a Python library for visualizing cortical surface
    representations of neuroimaging data. The package is primarily intended for
    use with Freesurfer, but it can plot data that are drawn from a variety of
    sources. PySurfer extends Mayavi’s powerful rendering engine with a
    high-level interface for working with MRI and MEG data.
  doc_url: http://pysurfer.github.io
  dev_url: https://github.com/nipy/PySurfer/

extra:
  recipe-maintainers:
    - christianbrodbeck
    - larsoner
