travis:
  secure:
    BINSTAR_TOKEN: oe2vYofWg9dPSOJVrC86M9aYsn4mbLqDkN4deZMm58wyjlkQpLeXdfec7ZxmgMf0ffrS/bjJ/rMtNyn7Sz95DisaT/egGCWntwIfogTv9s1/Wmod5752LJEWlns7KNmumCKRLr5Eqz7Tl4WdY0sZkV+Nd29+wW52YU+IA8Gwhhad7PhxCgbNDrX/if0JC6ortApCYvsXLMAkgzJW0aOAigr8IyqyrxQPuY85GU5LuB86rv8nK8ho2Qzn7QEGvJBcVhhNSbGAViiADIPlwmfHW57955CIX181k+scohJR82puLP2Pv0iPArA+w4HFUpf/c36pj+E4ID3/pfCdCmz1WRgnd88FtuooZE1BZpMn8Ze+KwW0ZARpL4koS6UhgSnHudHgXR7smoHYhK0Z/zFBZDC3l+XBFi+1R4w20gra5ejo6FVnaTbah5Ifk0jqCi+0/dWo5lfKhqOOfiJFUAJ8mBybkKyjDgJEVfC1XpRQnll5oNlVbrMbZcqH20J426cyWI6CJ0FBYlhYg1iAK8haVabaUBY1OInGlXsBK7gmNjLObyWAfGDa/tQO+v6yjUeVwAFvao5Q3N6+wlGWbdDz9nihRLQHnOh2bl91UKbl3ukJpXPGDqhqKZ21hpqxkCXujSKmUYmYEMOx9M4YUgAcrxptMfo45KC84LTcJLcgrWA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
